server:
  port: 2222

spring:
  application:
    name: geteway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/ #注册中心的访问地址
  instance:
    prefer-ip-address: true #将当前服务的ip注册到eureka server

zuul:
  routes:
    provider: /p/**
