server:
  port: 5789

spring:
  application:
    name: hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/ #注册中心的访问地址
  instance:
    prefer-ip-address: true #将当前服务的ip注册到eureka server


feign:
  hystrix:
    enabled: true



management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
