server:
  port: 1234

spring:
  application:
    name: ribbon

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/ #注册中心的访问地址
  instance:
    prefer-ip-address: true #将当前服务的ip注册到eureka server